export const Data = {
  menu: {
    starters: [
      {
        id: 1,
        name: 'coke',
        desc: 'Supergod rätt med rätt touch',
        category: 0,
        sizes: ['small', 'large'],
        price: 59,
      },
      {
        id: 2,
        name: 'pepsi',
        desc: 'Supergod rätt med rätt touch',
        category: 0,
        sizes: ['small', 'large'],
        price: 59,
      },
      {
        id: 3,
        name: 'water',
        category: 0,
        desc: 'Supergod rätt med rätt touch',
        sizes: ['small', 'large'],
        price: 59,
      },
      {
        id: 4,
        name: 'hamburger',
        category: 1,
        desc: 'Supergod rätt med rätt touch',
        sizes: ['small', 'large'],
        price: 59,
      },
      {
        id: 5,
        name: 'fries',
        category: 1,
        desc: 'Supergod rätt med rätt touch',
        sizes: ['small', 'large'],
        price: 59,
      },
      {
        id: 6,
        name: 'pizza',
        category: 1,
        desc: 'Supergod rätt med rätt touch',
        sizes: ['small', 'large'],
        price: 59,
      },
    ],
    mainCourse: [
      {
        id: 6,
        name: 'pizza',
        category: 1,
        desc: 'Supergod rätt med rätt touch',
        sizes: ['small', 'large'],
        price: 59,
      },
      {
        id: 6,
        name: 'pizza',
        category: 1,
        desc: 'Supergod rätt med rätt touch',
        sizes: ['small', 'large'],
        price: 59,
      },
      {
        id: 6,
        name: 'pizza',
        category: 1,
        desc: 'Supergod rätt med rätt touch',
        sizes: ['small', 'large'],
        price: 59,
      },
    ],
    desserts: [
      {
        id: 6,
        name: 'pizza',
        category: 1,
        desc: 'Supergod rätt med rätt touch',
        sizes: ['small', 'large'],
        price: 59,
      },
      {
        id: 6,
        name: 'pizza',
        category: 1,
        desc: 'Supergod rätt med rätt touch',
        sizes: ['small', 'large'],
        price: 59,
      },
      {
        id: 6,
        name: 'pizza',
        category: 1,
        desc: 'Supergod rätt med rätt touch',
        sizes: ['small', 'large'],
        price: 59,
      },
    ],
    drinks: [
      {
        id: 6,
        name: 'pizza',
        category: 1,
        desc: 'Supergod rätt med rätt touch',
        sizes: ['small', 'large'],
        price: 59,
      },
      {
        id: 6,
        name: 'pizza',
        category: 1,
        desc: 'Supergod rätt med rätt touch',
        sizes: ['small', 'large'],
        price: 59,
      },
      {
        id: 6,
        name: 'pizza',
        category: 1,
        desc: 'Supergod rätt med rätt touch',
        sizes: ['small', 'large'],
        price: 59,
      },
    ],
  },
};
